In [1]:
import pandas as pd
import numpy as np

In [2]:
county_mobility = pd.read_csv("County_Mobility_Report.csv")

In [3]:
Suffix_List = ["County"]
county_mobility["COUNTY"] = county_mobility["sub_region_2"].str.replace("\s?(" + "|".join(Suffix_List) + ")$", "")
county_mobility.head()

,country_region_code,country_region,STATE,sub_region_2,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,COUNTY
0,US,United States,Alabama,Autauga County,2/15/20,5.0,7.0,NaN,NaN,-4.0,NaN,Autauga
1,US,United States,Alabama,Autauga County,2/16/20,0.0,1.0,-23.0,NaN,-4.0,NaN,Autauga
2,US,United States,Alabama,Autauga County,2/17/20,8.0,0.0,NaN,NaN,-27.0,5.0,Autauga
3,US,United States,Alabama,Autauga County,2/18/20,-2.0,0.0,NaN,NaN,2.0,0.0,Autauga
4,US,United States,Alabama,Autauga County,2/19/20,-2.0,0.0,NaN,NaN,2.0,0.0,Autauga

In [5]:
combined_data = pd.read_csv("combined_csv.csv")
combined_data.head()

,date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,2/8/20,AirNow,10730023,3,6.7,ug/m3 LC,28,North Birmingham,1,100,88101,PM2.5 - Local Conditions,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
1,2/8/20,AirNow,10731005,3,6.0,ug/m3 LC,25,McAdory,1,100,88502,Acceptable PM2.5 AQI & Speciation Mass,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.331111,-87.003611
2,2/8/20,AirNow,10732003,3,7.9,ug/m3 LC,33,Wylam,1,100,88502,Acceptable PM2.5 AQI & Speciation Mass,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.499722,-86.924167
3,2/8/20,AirNow,10735003,3,5.8,ug/m3 LC,24,Corner,1,100,88502,Acceptable PM2.5 AQI & Speciation Mass,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.801667,-86.942500
4,2/8/20,AirNow,10736004,3,11.0,ug/m3 LC,46,Sloss Shuttlesworth,1,100,88502,Acceptable PM2.5 AQI & Speciation Mass,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.565278,-86.796389

In [7]:
grouped = pd.DataFrame(combined_data.groupby(['date','STATE','COUNTY']).mean()['DAILY_AQI_VALUE'])
grouped.head()

                            DAILY_AQI_VALUE
date    STATE   COUNTY
2/10/20 Alabama Jefferson              25.8
                Madison                23.0
                Montgomery             54.0
                Morgan                 19.0
                Russell                21.0

In [37]:
#grouped_by_state = grouped.unstack(level = 0)
#grouped_by_state.columns = grouped_by_state.columns.get_level_values(1)
#grouped_by_state

In [8]:
#all_data = pd.merge(combined_data, county_mobility, how='outer', left_on=["STATE","COUNTY","date"], right_on=["STATE","COUNTY","date"])
#all_data = grouped_by_state.merge(county_mobility, how='left', left_on=["STATE","COUNTY"], right_on=["STATE","COUNTY"])
all_data = grouped.merge(county_mobility, how='outer', left_on=["date","STATE","COUNTY"], right_on=["date","STATE","COUNTY"])
#merged_df = left_df.merge(right_df, how='inner', left_on=["A", "B"], right_on=["A2","B2"])
all_data.tail()

,date,STATE,COUNTY,DAILY_AQI_VALUE,country_region_code,country_region,sub_region_2,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
165178,4/6/20,Wyoming,Weston,NaN,US,United States,Weston County,NaN,NaN,NaN,NaN,-39.0,NaN
165179,4/7/20,Wyoming,Weston,NaN,US,United States,Weston County,NaN,NaN,NaN,NaN,-37.0,NaN
165180,4/8/20,Wyoming,Weston,NaN,US,United States,Weston County,NaN,NaN,NaN,NaN,-36.0,NaN
165181,4/9/20,Wyoming,Weston,NaN,US,United States,Weston County,NaN,NaN,NaN,NaN,-31.0,NaN
165182,4/10/20,Wyoming,Weston,NaN,US,United States,Weston County,NaN,NaN,NaN,NaN,-43.0,NaN

In [9]:
all_data.dtypes

date                                                   object
STATE                                                  object
COUNTY                                                 object
DAILY_AQI_VALUE                                       float64
country_region_code                                    object
country_region                                         object
sub_region_2                                           object
retail_and_recreation_percent_change_from_baseline    float64
grocery_and_pharmacy_percent_change_from_baseline     float64
parks_percent_change_from_baseline                    float64
transit_stations_percent_change_from_baseline         float64
workplaces_percent_change_from_baseline               float64
residential_percent_change_from_baseline              float64
dtype: object

In [10]:
all_data.to_csv("all_data.csv");

In [11]:
air_movement = all_data[pd.notnull(all_data['DAILY_AQI_VALUE'])]
air_movement.tail()

,date,STATE,COUNTY,DAILY_AQI_VALUE,country_region_code,country_region,sub_region_2,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
42482,4/9/20,Wisconsin,Waukesha,19.0,US,United States,Waukesha County,-47.0,-11.0,31.0,-29.0,-52.0,25.0
42483,4/9/20,Wyoming,Laramie,15.0,US,United States,Laramie County,-34.0,-9.0,59.0,-15.0,-43.0,17.0
42484,4/9/20,Wyoming,Natrona,15.0,US,United States,Natrona County,-30.0,2.0,28.0,-19.0,-37.0,14.0
42485,4/9/20,Wyoming,Sweetwater,6.0,US,United States,Sweetwater County,-29.0,2.0,NaN,4.0,-36.0,11.0
42486,4/9/20,Wyoming,Teton,2.0,US,United States,Teton County,NaN,NaN,-59.0,NaN,-56.0,NaN

In [12]:
air_movement = all_data[pd.notnull(all_data['residential_percent_change_from_baseline'])]
air_movement.head()

,date,STATE,COUNTY,DAILY_AQI_VALUE,country_region_code,country_region,sub_region_2,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
2819,2/15/20,Alabama,Jefferson,31.2,US,United States,Jefferson County,4.0,1.0,109.0,3.0,2.0,0.0
2820,2/15/20,Alabama,Madison,26.0,US,United States,Madison County,2.0,1.0,49.0,4.0,3.0,-1.0
2821,2/15/20,Alabama,Montgomery,51.0,US,United States,Montgomery County,6.0,1.0,56.0,6.0,3.0,-1.0
2822,2/15/20,Alabama,Morgan,25.0,US,United States,Morgan County,7.0,6.0,55.0,6.0,3.0,0.0
2823,2/15/20,Alabama,Russell,31.0,US,United States,Russell County,9.0,3.0,NaN,NaN,-2.0,-1.0

In [10]:
air_movement.to_csv("air_movement_changes.csv");