In [1]:
import pandas as pd
import numpy as np

In [2]:
county_mobility = pd.read_csv("County_Mobility_Report.csv")

In [3]:
Suffix_List = ["County"]
county_mobility["COUNTY"] = county_mobility["sub_region_2"].str.replace("\s?(" + "|".join(Suffix_List) + ")$", "")
county_mobility.head()

,country_region_code,country_region,STATE,sub_region_2,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,COUNTY
0,US,United States,Alabama,Autauga County,2/15/20,5.0,7.0,NaN,NaN,-4.0,NaN,Autauga
1,US,United States,Alabama,Autauga County,2/16/20,0.0,1.0,-23.0,NaN,-4.0,NaN,Autauga
2,US,United States,Alabama,Autauga County,2/17/20,8.0,0.0,NaN,NaN,-27.0,5.0,Autauga
3,US,United States,Alabama,Autauga County,2/18/20,-2.0,0.0,NaN,NaN,2.0,0.0,Autauga
4,US,United States,Alabama,Autauga County,2/19/20,-2.0,0.0,NaN,NaN,2.0,0.0,Autauga

In [4]:
combined_data = pd.read_csv("combined_csv.csv")
combined_data.head()

,date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,2/8/20,AirNow,10730023,3,6.7,ug/m3 LC,28,North Birmingham,1,100,88101,PM2.5 - Local Conditions,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.553056,-86.815000
1,2/8/20,AirNow,10731005,3,6.0,ug/m3 LC,25,McAdory,1,100,88502,Acceptable PM2.5 AQI & Speciation Mass,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.331111,-87.003611
2,2/8/20,AirNow,10732003,3,7.9,ug/m3 LC,33,Wylam,1,100,88502,Acceptable PM2.5 AQI & Speciation Mass,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.499722,-86.924167
3,2/8/20,AirNow,10735003,3,5.8,ug/m3 LC,24,Corner,1,100,88502,Acceptable PM2.5 AQI & Speciation Mass,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.801667,-86.942500
4,2/8/20,AirNow,10736004,3,11.0,ug/m3 LC,46,Sloss Shuttlesworth,1,100,88502,Acceptable PM2.5 AQI & Speciation Mass,13820.0,"Birmingham-Hoover, AL",1,Alabama,73,Jefferson,33.565278,-86.796389

In [12]:
#all_data = pd.merge(combined_data, county_mobility, how='outer', left_on=["STATE","COUNTY","date"], right_on=["STATE","COUNTY","date"])
all_data = combined_data.merge(county_mobility, how='outer', left_on=["STATE","COUNTY","date"], right_on=["STATE","COUNTY","date"])
#merged_df = left_df.merge(right_df, how='inner', left_on=["A", "B"], right_on=["A2","B2"])
all_data.head(100)

,date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,...,SITE_LONGITUDE,country_region_code,country_region,sub_region_2,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,2/8/20,AirNow,10730023.0,3.0,6.7,ug/m3 LC,28.0,North Birmingham,1.0,100.0,...,-86.815000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2/8/20,AirNow,10731005.0,3.0,6.0,ug/m3 LC,25.0,McAdory,1.0,100.0,...,-87.003611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2/8/20,AirNow,10732003.0,3.0,7.9,ug/m3 LC,33.0,Wylam,1.0,100.0,...,-86.924167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2/8/20,AirNow,10735003.0,3.0,5.8,ug/m3 LC,24.0,Corner,1.0,100.0,...,-86.942500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2/8/20,AirNow,10736004.0,3.0,11.0,ug/m3 LC,46.0,Sloss Shuttlesworth,1.0,100.0,...,-86.796389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2/27/20,AirNow,10736004.0,3.0,9.0,ug/m3 LC,38.0,Sloss Shuttlesworth,1.0,100.0,...,-86.796389,US,United States,Jefferson County,11.0,7.0,5.0,4.0,2.0,-1.0
96,2/28/20,AirNow,10730023.0,3.0,6.7,ug/m3 LC,28.0,North Birmingham,1.0,100.0,...,-86.815000,US,United States,Jefferson County,10.0,5.0,20.0,6.0,1.0,-1.0
97,2/28/20,AirNow,10731005.0,3.0,5.7,ug/m3 LC,24.0,McAdory,1.0,100.0,...,-87.003611,US,United States,Jefferson County,10.0,5.0,20.0,6.0,1.0,-1.0
98,2/28/20,AirNow,10732003.0,3.0,4.0,ug/m3 LC,17.0,Wylam,1.0,100.0,...,-86.924167,US,United States,Jefferson County,10.0,5.0,20.0,6.0,1.0,-1.0
99,2/28/20,AirNow,10735003.0,3.0,3.5,ug/m3 LC,15.0,Corner,1.0,100.0,...,-86.942500,US,United States,Jefferson County,10.0,5.0,20.0,6.0,1.0,-1.0

In [13]:
all_data.tail()

,date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,...,SITE_LONGITUDE,country_region_code,country_region,sub_region_2,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
187281,4/6/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,US,United States,Weston County,NaN,NaN,NaN,NaN,-39.0,NaN
187282,4/7/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,US,United States,Weston County,NaN,NaN,NaN,NaN,-37.0,NaN
187283,4/8/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,US,United States,Weston County,NaN,NaN,NaN,NaN,-36.0,NaN
187284,4/9/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,US,United States,Weston County,NaN,NaN,NaN,NaN,-31.0,NaN
187285,4/10/20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,US,United States,Weston County,NaN,NaN,NaN,NaN,-43.0,NaN

In [14]:
air_movement = all_data[pd.notnull(all_data['residential_percent_change_from_baseline'])]
air_movement.head()

,date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,...,SITE_LONGITUDE,country_region_code,country_region,sub_region_2,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
35,2/15/20,AirNow,10730023.0,3.0,8.1,ug/m3 LC,34.0,North Birmingham,1.0,100.0,...,-86.815000,US,United States,Jefferson County,4.0,1.0,109.0,3.0,2.0,0.0
36,2/15/20,AirNow,10731005.0,3.0,6.7,ug/m3 LC,28.0,McAdory,1.0,100.0,...,-87.003611,US,United States,Jefferson County,4.0,1.0,109.0,3.0,2.0,0.0
37,2/15/20,AirNow,10732003.0,3.0,9.6,ug/m3 LC,40.0,Wylam,1.0,100.0,...,-86.924167,US,United States,Jefferson County,4.0,1.0,109.0,3.0,2.0,0.0
38,2/15/20,AirNow,10735003.0,3.0,5.4,ug/m3 LC,23.0,Corner,1.0,100.0,...,-86.942500,US,United States,Jefferson County,4.0,1.0,109.0,3.0,2.0,0.0
39,2/15/20,AirNow,10736004.0,3.0,7.4,ug/m3 LC,31.0,Sloss Shuttlesworth,1.0,100.0,...,-86.796389,US,United States,Jefferson County,4.0,1.0,109.0,3.0,2.0,0.0

In [ ]:
air_movement.to_csv("air_movement_changes");

In [48]:
#frames = [combined_data, county_mobility]

#result = pd.concat(frames)

#result = pd.concat([combined_data, county_mobility], ignore_index=True, sort=False)
result = county_mobility.append(combined_data, ignore_index=True, sort=False)
result.dropna(subset=['DAILY_AQI_VALUE'])
result.head()

,country_region_code,country_region,sub_region_1,sub_region_2,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,...,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,US,United States,Alabama,Autauga County,2/15/20,5.0,7.0,NaN,NaN,-4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,US,United States,Alabama,Autauga County,2/16/20,0.0,1.0,-23.0,NaN,-4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,US,United States,Alabama,Autauga County,2/17/20,8.0,0.0,NaN,NaN,-27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,US,United States,Alabama,Autauga County,2/18/20,-2.0,0.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,US,United States,Alabama,Autauga County,2/19/20,-2.0,0.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,US,United States,Alabama,Conecuh County,3/15/20,16.0,20.0,NaN,25.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,US,United States,Alabama,Conecuh County,3/16/20,-24.0,29.0,NaN,7.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,US,United States,Alabama,Conecuh County,3/17/20,-16.0,12.0,NaN,1.0,-9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,US,United States,Alabama,Conecuh County,3/18/20,-31.0,NaN,NaN,-6.0,-6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,US,United States,Alabama,Conecuh County,3/19/20,-19.0,24.0,NaN,1.0,-13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
result = county_mobility.append(combined_data, sort=False)
result.head()

,country_region_code,country_region,sub_region_1,sub_region_2,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,...,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,US,United States,Alabama,Autauga County,2/15/20,5.0,7.0,NaN,NaN,-4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,US,United States,Alabama,Autauga County,2/16/20,0.0,1.0,-23.0,NaN,-4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,US,United States,Alabama,Autauga County,2/17/20,8.0,0.0,NaN,NaN,-27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,US,United States,Alabama,Autauga County,2/18/20,-2.0,0.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,US,United States,Alabama,Autauga County,2/19/20,-2.0,0.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
#result[result['DAILY_AQI_VALUE'].notna()]
#result.dropna(subset=['DAILY_AQI_VALUE'])

,country_region_code,country_region,sub_region_1,sub_region_2,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,...,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88101.0,PM2.5 - Local Conditions,12100.0,"Atlantic City-Hammonton, NJ",34.0,New Jersey,1.0,Atlantic,39.464872,-74.448736
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88101.0,PM2.5 - Local Conditions,12100.0,"Atlantic City-Hammonton, NJ",34.0,New Jersey,1.0,Atlantic,39.464872,-74.448736
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88101.0,PM2.5 - Local Conditions,12100.0,"Atlantic City-Hammonton, NJ",34.0,New Jersey,1.0,Atlantic,39.464872,-74.448736
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88101.0,PM2.5 - Local Conditions,12100.0,"Atlantic City-Hammonton, NJ",34.0,New Jersey,1.0,Atlantic,39.464872,-74.448736
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88101.0,PM2.5 - Local Conditions,12100.0,"Atlantic City-Hammonton, NJ",34.0,New Jersey,1.0,Atlantic,39.464872,-74.448736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99919,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88101.0,PM2.5 - Local Conditions,41540.0,"Salisbury, MD-DE",10.0,Delaware,5.0,Sussex,38.653900,-75.610600
99920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88101.0,PM2.5 - Local Conditions,41540.0,"Salisbury, MD-DE",10.0,Delaware,5.0,Sussex,38.653900,-75.610600
99921,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88101.0,PM2.5 - Local Conditions,41540.0,"Salisbury, MD-DE",10.0,Delaware,5.0,Sussex,38.653900,-75.610600
99922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88101.0,PM2.5 - Local Conditions,41540.0,"Salisbury, MD-DE",10.0,Delaware,5.0,Sussex,38.653900,-75.610600
99923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88101.0,PM2.5 - Local Conditions,41540.0,"Salisbury, MD-DE",10.0,Delaware,5.0,Sussex,38.653900,-75.610600

In [16]:
def get_AQI_Value(STATE, COUNTY, Date):
    try:
        return combined_data.loc[STATE][COUNTY][Date]
    except:
        return np.NaN

nan

In [6]:
#grouped = pd.DataFrame(combined_data.groupby(['STATE','COUNTY', 'Date']).mean()['DAILY_AQI_VALUE'])
#grouped.head()

                           DAILY_AQI_VALUE
STATE   COUNTY    Date
Alabama Jefferson 1/1/20         30.833333
                  1/10/20        39.000000
                  1/11/20        26.666667
                  1/12/20        27.166667
                  1/13/20        35.333333